WIP Created entity and 1:1 with Cart
piotr-grosicki/project-jdp-2010-01 pull request #20
Opened 2020-10-27 19:45 UTC by Hamonnah

2020-10-28 13:58 UTC, andzia0520 commented on src/main/java/com/kodilla/ecommercee/domain/User.java
> +@Table(name = "USER")
czy nie lepiej byłoby w nazwie tabeli dać liczbę mnogą? "USERS" zamiast USER ?

2020-10-28 13:58 UTC, andzia0520 commented on src/main/java/com/kodilla/ecommercee/domain/User.java
>      private boolean status;
proponuję zmianę nazwy pola ze status na isBlocked bądź isActive  - tu chodzi o to czy konto ma aktywne czy zablokowane  to wg mnie byłoby czytelniejsze

2020-10-28 13:58 UTC, andzia0520 commented on src/main/java/com/kodilla/ecommercee/domain/User.java
> +    @JoinColumn(name = "CART")
wg mnie powinno być name "CART_ID" a nie "CART"

2020-10-28 13:58 UTC, andzia0520 commented on src/main/java/com/kodilla/ecommercee/domain/User.java
> +    public void setId(Long id) {
CZy wszystkie settery nie powinny być private?

2020-10-28 13:58 UTC, andzia0520 commented on src/main/java/com/kodilla/ecommercee/repository/UserRepository.java
> +public interface UserRepository extends CrudRepository<User, Long> {
zgodnie z ustaleniami na komunikatorze mieliśmy nie dodawać żadnych klas poza encją, bo rzeczywista implementacja jest w kolejnych taskach

2020-10-28 13:58 UTC, andzia0520 commented on src/main/java/com/kodilla/ecommercee/domain/User.java
> +@Table(name = "USER")
chyba że ja to sobie potem mam proprawić bo to moja encja

2020-10-28 14:31 UTC, piotr-grosicki requested changes
rzeczy do poprawy w komentarzach

2020-10-28 14:31 UTC, piotr-grosicki commented on src/main/java/com/kodilla/ecommercee/domain/User.java
>      private boolean status;
jestem za, ale pole nie powinno miec w swojej nazwie `is`, wystarczy `active` lub `blocked`

2020-10-28 14:31 UTC, piotr-grosicki commented on src/main/java/com/kodilla/ecommercee/domain/User.java
> +    public void setId(Long id) {
settery nigdy nie powinny byc private

2020-10-29 07:36 UTC, piotr-grosicki requested changes

2020-10-29 07:36 UTC, piotr-grosicki commented on src/main/java/com/kodilla/ecommercee/domain/Cart.java
> +    private Order order;
brakuje definicji relacji do order

2020-10-29 07:36 UTC, piotr-grosicki commented on src/main/java/com/kodilla/ecommercee/domain/Cart.java
> +    private Order order;
swoja droga czemu ta relacja powstala.w tym pull requescie? jezeli robisz usera to powinna powstac tylko wydmuszka Cart, ktora pozwala ci podpiac te encje do encji usera.

2020-10-29 08:50 UTC, Hamonnah commented on src/main/java/com/kodilla/ecommercee/domain/Cart.java
> +    private Order order;
Pisałam na forum, ze nie rozumiem co znaczy klasa wydmuszka. I pisałam także ze żeby zrobić moja relacje przepisałam potrzebne mi elementy z pulla Ani klasy Cart. Zapytalam czy mogę to wypuszowac i nikt nie zgłosił sprzeciw, a Ania powiedziała, ze chyba Tobie o to chodziło z tymi wydmuszkami.

2020-10-29 08:53 UTC, Hamonnah commented on src/main/java/com/kodilla/ecommercee/domain/Cart.java
> +    private Order order;
Albo inaczej, skopiowałam kod Ani i wywalilam wszystko co powodowało blad, a co nie powodowało poprostu zostało.

2020-10-29 12:42 UTC, piotr-grosicki commented on src/main/java/com/kodilla/ecommercee/domain/Cart.java
> +    private Order order;
ale ok, niech bedzie tak jak jest teraz, na przyszlosc juz wiesz :)

2020-10-29 12:43 UTC, merged