JDP201001-14
piotr-grosicki/project-jdp-2010-01 pull request #31
Opened 2020-10-30 16:08 UTC by andzia0520

2020-10-30 20:12 UTC, dud3k88 commented
Hej Ania prześlij proszę jeszcze raz bo mój genialny synek coś namieszał mi na komputerze i chyba usunął Twojego brancha :(

2020-10-30 20:58 UTC, dud3k88 approved these changes

2020-10-31 16:30 UTC, piotr-grosicki requested changes

2020-10-31 16:30 UTC, piotr-grosicki commented on src/main/java/com/kodilla/ecommercee/domain/CartDto.java
> +    private User user;
klasy Dto nie moga zawierac klas encji, Product tutaj tez jest niepoprawnie (nie zauwazylem wczesniej). powinny byc tutaj klasy Dto

2020-10-31 16:35 UTC, andzia0520 commented on src/main/java/com/kodilla/ecommercee/domain/CartDto.java
> +    private User user;
nie rozumiem co masz na myśli "klasy Dto nie moga zawierac klas encji," ?
mam z DTO wyrzucic User user ?

2020-10-31 16:58 UTC, dud3k88 commented on src/main/java/com/kodilla/ecommercee/domain/CartDto.java
> +    private User user;
Powinno być userdto które nie jest encja

2020-10-31 20:55 UTC, piotr-grosicki commented on src/main/java/com/kodilla/ecommercee/domain/CartDto.java
> +    private User user;
dokladnie tak jak @dud3k88 napisal

2020-11-01 09:37 UTC, piotr-grosicki approved these changes

2020-11-01 09:37 UTC, merged