Zadanie JDP201001-20
piotr-grosicki/project-jdp-2010-01 pull request #33
Opened 2020-11-02 13:06 UTC by dud3k88

- Utworzenie testów encji User. 
- dodanie konstruktora do klasy Cart z parametrem Id
- utworzenie na potrzeby testu controllera repozytorium CartDao
- zmieniłem nazwy kontrolerów z końcówką -Dao (zgodnie z materiałami)

@andzia0520  dodałem Cie do Reviewersów ponieważ pracowałaś nad encją Cart.

2020-11-02 19:43 UTC, andzia0520 approved these changes

2020-11-03 07:58 UTC, piotr-grosicki requested changes

2020-11-03 07:58 UTC, piotr-grosicki commented on src/test/java/com/kodilla/ecommercee/user/dao/UserDaoTestSuite.java
> +    public void deleteUserByIdTestSuite() {
brakuje sprawdzenia czy cart jest usuwany podczas usuniecia uzytkownika? do ustalenia w ogole czy powinien :)

2020-11-04 08:01 UTC, piotr-grosicki approved these changes

2020-11-04 08:01 UTC, merged