Jdp201001 poprawa
piotr-grosicki/project-jdp-2010-01 pull request #36
Opened 2020-11-02 22:35 UTC by IngaPanczyk

2020-11-02 22:39 UTC, IngaPanczyk commented
Sorki, za marnowanie Twojego czasu, nie wrzuciłam najaktualniejszej wersji.

2020-11-03 07:59 UTC, piotr-grosicki requested changes

2020-11-03 07:59 UTC, piotr-grosicki commented on src/test/java/com/kodilla/ecommercee/productDao/ProductDaoTestSuite.java
> +    public void deleteProductByIdTestSuite() {
brakuje sprawdzenia co sie dzieje z relacjami podczas usuniecia produktu, ktore powinny byc usuniete, ktore powinny zostac

2020-11-03 20:37 UTC, IngaPanczyk commented on src/test/java/com/kodilla/ecommercee/productDao/ProductDaoTestSuite.java
Grupa i Cart nie są usuwane razem z produktem, co dla mnie jest logiczne. Czy o takie sprawdzenie zależności chodziło?

2020-11-04 08:00 UTC, piotr-grosicki commented on src/test/java/com/kodilla/ecommercee/productDao/ProductDaoTestSuite.java
tak, czekamy az ktos sprawdzi PR

2020-11-04 09:56 UTC, dud3k88 approved these changes

2020-11-04 14:51 UTC, closed without merging

2020-11-04 14:52 UTC, IngaPanczyk commented
Zamykam PR dopuki nie rozwiążę konfliktów