JDP201001-19
piotr-grosicki/project-jdp-2010-01 pull request #41
Opened 2020-11-06 20:13 UTC by andzia0520

Było tak dużo zmian, że zrobiłam nowy branch. Testy poprawione.

2020-11-06 21:07 UTC, IngaPanczyk commented
Dla mnie wszystko ok

2020-11-06 21:09 UTC, IngaPanczyk approved these changes

2020-11-07 08:43 UTC, piotr-grosicki requested changes

2020-11-07 08:43 UTC, piotr-grosicki commented on src/test/java/com/kodilla/ecommercee/CartDaoTestSuite.java
> +        Assert.assertTrue(usersBeforeDelete.size() > usersAfterDelete.size());
usuniecie carta skutkuje usunieciem uzytkownika ze sklepu? :)

2020-11-07 09:31 UTC, andzia0520 commented on src/test/java/com/kodilla/ecommercee/CartDaoTestSuite.java
> +        Assert.assertTrue(usersBeforeDelete.size() > usersAfterDelete.size());
Albo kupuje albo usuwamy :) Poprawiłam asercje i cascade w Cart. Proszę o ponowne sprawdzenie

2020-11-08 19:42 UTC, dud3k88 commented on src/test/java/com/kodilla/ecommercee/CartDaoTestSuite.java
> +        Assert.assertNotEquals(0, cart3Id);
Przypisujesz product do Cart ale nigdzie tego nie sprawdzasz. Do ilu kart przypisany jest dany produkt. Myślę że w drugą stronę też powinno to działać czyli, ile dana karta zawiera produktów.

2020-11-09 07:29 UTC, piotr-grosicki requested changes
konflikty

2020-11-09 18:09 UTC, piotr-grosicki commented on src/test/java/com/kodilla/ecommercee/CartDaoTestSuite.java
> +        cart.setUser(piotr);
cart bez usera nie ma sensu i powinien sie nie dac zapisac

2020-11-09 18:09 UTC, piotr-grosicki requested changes
projekt sie nie buduje

2020-11-09 18:15 UTC, andzia0520 commented on src/test/java/com/kodilla/ecommercee/CartDaoTestSuite.java
> +        Assert.assertNotEquals(0, cart3Id);
przejęłam że sprawdzenie w drugą stronę robią testy encji Product

2020-11-09 21:53 UTC, andzia0520 commented on src/test/java/com/kodilla/ecommercee/CartDaoTestSuite.java
> +        cart.setUser(piotr);
dorobiłam asercje nie wiem czy o to chodziło

2020-11-09 22:21 UTC, andzia0520 commented
> konflikty

po długotrwałej walce powinno być OK

2020-11-09 22:21 UTC, andzia0520 commented
> projekt sie nie buduje

powinno być ok

2020-11-10 14:09 UTC, piotr-grosicki requested changes

2020-11-10 14:09 UTC, piotr-grosicki commented on src/test/java/com/kodilla/ecommercee/CartDaoTestSuite.java
> +        cart.setUser(piotr);
rzeczywiscie ta linijka nie ma sensu bo przeciez usera przekazujesz w konstruktorze w linijce 97 ;)

2020-11-10 14:09 UTC, piotr-grosicki commented on src/test/java/com/kodilla/ecommercee/CartDaoTestSuite.java
> +        cart.setUser(user);
user juz jest przekazany do carta w konstruktorze

2020-11-10 15:13 UTC, andzia0520 commented on src/test/java/com/kodilla/ecommercee/CartDaoTestSuite.java
> +        cart.setUser(piotr);
poprawione

2020-11-10 15:13 UTC, andzia0520 commented on src/test/java/com/kodilla/ecommercee/CartDaoTestSuite.java
> +        cart.setUser(user);
poprawione

2020-11-11 08:55 UTC, andzia0520 commented on src/test/java/com/kodilla/ecommercee/CartDaoTestSuite.java
> +        Assert.assertNotEquals(0, cart3Id);
poprawione

2020-11-12 09:18 UTC, piotr-grosicki approved these changes

2020-11-12 09:18 UTC, merged