JDP201001-16 TestyEncjiOrder
piotr-grosicki/project-jdp-2010-01 pull request #42
Opened 2020-11-07 22:04 UTC by Ryba218

Testy encji Order

2020-11-07 22:22 UTC, andzia0520 requested changes

2020-11-07 22:22 UTC, andzia0520 commented on src/test/java/com/kodilla/ecommercee/order/dao/OrderDaoTestSuite.java
> +    }
w testach brakuje sprawdzenia co sie dzieje z cart jak usuwasz Order

2020-11-07 22:23 UTC, dud3k88 requested changes

2020-11-07 22:23 UTC, dud3k88 commented on src/test/java/com/kodilla/ecommercee/order/dao/OrderDaoTestSuite.java
> +        Assert.assertFalse(orderDao.findById(id).isPresent());
Powinieneś sprawdzić czy karta też została usunięta.
Z relacji wynika że podczas usunięcia zamówienia usuwa się również karta.

2020-11-07 22:23 UTC, dud3k88 commented on src/main/java/com/kodilla/ecommercee/repository/OrderDao.java
> +    Order save(Order order);
Brakuje testu :)

2020-11-08 20:10 UTC, dud3k88 approved these changes

2020-11-09 07:25 UTC, piotr-grosicki approved these changes

2020-11-09 07:25 UTC, merged