Jdp201001 17 poprawa testów
piotr-grosicki/project-jdp-2010-01 pull request #43
Opened 2020-11-08 07:58 UTC by IngaPanczyk

2020-11-08 08:01 UTC, IngaPanczyk commented
Niestety musiałam zrobić nową gałąź. Testy poprawiony, proszę o sprawdzenie.

2020-11-08 10:20 UTC, Hamonnah requested changes
Poza drobnymi uwagami, wydaje mi sie, ze jest ok.

2020-11-08 10:20 UTC, Hamonnah commented on src/test/java/com/kodilla/ecommercee/productDao/ProductDaoTestSuite.java
> +    public void saveProductOnDatabaseTestSuite() {
Wydaje mi sie, ze nie powinno sie używać  Suite w nazwie pojedynczych testów.  Suite używa sie raczej do nazwania grupy testów.

2020-11-08 10:20 UTC, Hamonnah commented on src/test/java/com/kodilla/ecommercee/productDao/ProductDaoTestSuite.java
> +        User user3 = new User ("Janina");
Czy User jest niezbędny przy teście zapisu produktu z koszykiem? Test przechodzi również bez Usera. Moim zdaniem User nic nie wnosi.

2020-11-08 10:20 UTC, Hamonnah commented on src/test/java/com/kodilla/ecommercee/productDao/ProductDaoTestSuite.java
> +
Brakuje spacji przed "=" , żeby było ładne i spójnie z reszta ;)

2020-11-08 10:20 UTC, Hamonnah commented on src/test/java/com/kodilla/ecommercee/productDao/ProductDaoTestSuite.java
> +        User user = new User("Adam");
Ten test tez można zrobić bez Usera.. Wydaje mi sie, ze im mniej zależności w teście tym bardziej specyficzny bedzie.

2020-11-08 11:03 UTC, IngaPanczyk commented on src/test/java/com/kodilla/ecommercee/productDao/ProductDaoTestSuite.java
> +    public void saveProductOnDatabaseTestSuite() {
Przyznaję, że nie zastanawiałam się nad tym.  Chciałam aby nazwy testów były zgodne. a testy do Usera nazywają się UserDaoTestSuite.

2020-11-08 11:09 UTC, IngaPanczyk commented on src/test/java/com/kodilla/ecommercee/productDao/ProductDaoTestSuite.java
> +        User user3 = new User ("Janina");
Test deleteProductByIdTestSuite nie przechodzi bez Usera, pojawia się błąd związany z faktem, że ustawiam id dla Carta a pole jest @GeneratedValue(strategy = GenerationType.AUTO), przynajmniej takie informacje znalazłam w sieci.  W związku z powyższych chciałam aby inne testy też miały Usera.

2020-11-08 11:11 UTC, IngaPanczyk commented on src/test/java/com/kodilla/ecommercee/productDao/ProductDaoTestSuite.java
> +        User user = new User("Adam");
Zgadzam się, ale tak jak pisałam mi pojawia się błąd i dopiero dodanie Usera go rozwiązało. Czy robiłaś ten konkretny test bez Usera? Jeśli tak, jak wyglądał Cart?

2020-11-08 11:11 UTC, IngaPanczyk commented on src/test/java/com/kodilla/ecommercee/productDao/ProductDaoTestSuite.java
> +
Oczywiście, poprawię:-)

2020-11-08 11:54 UTC, Hamonnah commented on src/test/java/com/kodilla/ecommercee/productDao/ProductDaoTestSuite.java
> +
Mam jeszcze uwagę do tego testu. Czy to nie powinna być lista produktów które zapisujemy w grupie? Czy te produkty sie zapisują w grupie?

2020-11-08 11:55 UTC, Hamonnah commented on src/test/java/com/kodilla/ecommercee/productDao/ProductDaoTestSuite.java
> +        Assert.assertTrue(groupResult.isPresent());
Tu sprawdzasz czy jest produkt i czy jest grupa, ale jaki one maja związek/relacje to juz nie sprawdzasz.

2020-11-08 11:59 UTC, Hamonnah commented on src/test/java/com/kodilla/ecommercee/productDao/ProductDaoTestSuite.java
> +        User user3 = new User ("Janina");
Mozna zrobic tak:  Cart cart1 = new Cart(); ? bez podawania User jako argument?

2020-11-08 12:01 UTC, Hamonnah commented on src/test/java/com/kodilla/ecommercee/productDao/ProductDaoTestSuite.java
> +        User user = new User("Adam");
Ja zrobilam tak: Cart cart = new Cart(); i przeszlo.
Natomiast nie jestem pewna czy to jest dobrze

2020-11-08 12:33 UTC, IngaPanczyk commented on src/test/java/com/kodilla/ecommercee/productDao/ProductDaoTestSuite.java
> +        User user = new User("Adam");
Mi oczywiście też pusty przechodzi, ale wydaje mi się, że Cart powinien coś zawierać, aby sprawdzić funkcjonowanie programu. @piotr-grosicki proszę o informację, czy mogę tak uprościć testy

2020-11-08 12:41 UTC, IngaPanczyk commented on src/test/java/com/kodilla/ecommercee/productDao/ProductDaoTestSuite.java
> +
Zastanawiałam się nad tym i dodałam `group.getProductList().add(product);`. Chociaż jeśli `Optional<Group>groupResult = groupDao.findById(group.getId());` i assercja `Assert.assertTrue(groupResult.isPresent());` jest ok, to zakładam, że utworzony produkt istnieje w grupie

2020-11-08 12:59 UTC, IngaPanczyk commented on src/test/java/com/kodilla/ecommercee/productDao/ProductDaoTestSuite.java
> +        Assert.assertTrue(groupResult.isPresent());
W moim rozumieniu zapisuję określony produkt w bazie po wcześniejszym ustawieniu jego pola grup, na podaną grupę. Następnie zapisuję sam produkt. W teście sprawdzam, czy produkt i grupa istnieją w bazie. Zakładam, że grupa nie mogłaby się pojawić w bazie, bez tego zapisu.  Jeśli jest, to znów zakładam że zapis był poprawny. Nie czuję się ekspertem, więc jeśli u siebie sprawdzasz relacje to chętnie się nauczę.

2020-11-08 20:03 UTC, dud3k88 commented on src/test/java/com/kodilla/ecommercee/productDao/ProductDaoTestSuite.java
>          cart3.getProductsAddedToCart().add(product3);
Myśle że ten zapis jest niepotrzebny ponieważ w sekcji when zapisujesz produkt do bazy a nie kartę.
Następnie sprawdzasz asercją co się dzieje w productDao. 
ID card pobierzesz ponieważ są przypisane do produktów :)

2020-11-09 07:19 UTC, piotr-grosicki commented on src/test/java/com/kodilla/ecommercee/productDao/ProductDaoTestSuite.java
> +    public void saveProductOnDatabaseTestSuite() {
potwierdzam, suite moze odnosic sie do klasy testowej, pojedynczy test raczej nie jestes suitem :)

2020-11-09 07:20 UTC, piotr-grosicki commented on src/test/java/com/kodilla/ecommercee/productDao/ProductDaoTestSuite.java
> +        Assert.assertTrue(groupResult.isPresent());
tak jak wspominalem na spotkaniu, na potrzeby tego projektu wystarczy. normalnie raczej bysmy chcieli sprawdzic co dokladnie sie zapisuje i czy relacje sa poprawne :)

2020-11-09 07:21 UTC, piotr-grosicki commented on src/test/java/com/kodilla/ecommercee/productDao/ProductDaoTestSuite.java
> +        User user3 = new User ("Janina");
`Cart` bez `User` nie ma sensu wiec raczej nie robilbym takiego testu, a nawet zweryfikowalbym czemu da sie utworzyc `Cart`, ktory nie posiada uzytkownika (brzmi troszke jak bug)

2020-11-09 07:22 UTC, piotr-grosicki commented on src/test/java/com/kodilla/ecommercee/productDao/ProductDaoTestSuite.java
> +        User user = new User("Adam");
odpisalem juz wyzej, `Cart` bez `User` nie ma sensu wiec nalezy sprawdzic dlaczego `new Cart()` przechodzi i zglosic do jako bug

2020-11-09 07:49 UTC, IngaPanczyk commented on src/test/java/com/kodilla/ecommercee/productDao/ProductDaoTestSuite.java
> +        User user = new User("Adam");
Zadanie dodane JDP201001-32

2020-11-09 07:50 UTC, IngaPanczyk commented on src/test/java/com/kodilla/ecommercee/productDao/ProductDaoTestSuite.java
> +        User user3 = new User ("Janina");
Tak jak wyżej, zadanie dodane JDP201001-32

2020-11-09 07:59 UTC, IngaPanczyk commented on src/test/java/com/kodilla/ecommercee/productDao/ProductDaoTestSuite.java
>          cart3.getProductsAddedToCart().add(product3);
Masz rację, poprawione

2020-11-09 08:03 UTC, IngaPanczyk commented on src/test/java/com/kodilla/ecommercee/productDao/ProductDaoTestSuite.java
> +
Po zastanowieniu się się, zrezygnowałam z zapisu `group.getProductList().add(product); ` (moim zdaniem nie wnosił nic do testu), ponieważ podczas zapisu produktu zapisuję również utworzoną grupę.

2020-11-09 08:36 UTC, IngaPanczyk commented
Naniosłam poprawki. Proszę o ponowne sprawdzenie

2020-11-09 12:53 UTC, Ryba218 approved these changes
Wygląda, że wszelkie kwestie zostały rozwiązane przy poprzednich reviews :)

2020-11-09 18:10 UTC, piotr-grosicki approved these changes

2020-11-09 18:10 UTC, merged