Jdp201001 18
piotr-grosicki/project-jdp-2010-01 pull request #46
Opened 2020-11-09 19:55 UTC by Hamonnah

2020-11-09 20:26 UTC, IngaPanczyk requested changes

2020-11-09 20:26 UTC, IngaPanczyk commented on src/test/java/com/kodilla/ecommercee/group/dao/GroupDaoTestSuite.java
> +        Assert.assertEquals("Chemia gospodarcza", group.getGroupName());
Czy linijka `Assert.assertEquals("Chemia gospodarcza", group.getGroupName());` jest niezbędna? sprawdzasz nią, czy setter dla group działa

2020-11-09 20:26 UTC, IngaPanczyk commented on src/test/java/com/kodilla/ecommercee/group/dao/GroupDaoTestSuite.java
> +        Assert.assertTrue(readGroup.isPresent());
Tworzysz dwa produkty a testujesz tylko  product1Td

2020-11-09 20:26 UTC, IngaPanczyk commented on src/test/java/com/kodilla/ecommercee/group/dao/GroupDaoTestSuite.java
> +}
Myślę, że warto byłoby sprawdzić co się dzieje z produktem jak usuwasz grupę. Czyli w takiej sytuacji jak w Twoim teście `saveProductsInGroupTest()`

2020-11-10 19:47 UTC, Hamonnah commented on src/test/java/com/kodilla/ecommercee/group/dao/GroupDaoTestSuite.java
> +}
Tez nad tym myślałam ale doszłam do wniosku ze to raczej powinno sie testować w produkcie, bo ja testuje co sie dzieje z grupa, a nie z produktem.

2020-11-11 20:15 UTC, dud3k88 commented on src/test/java/com/kodilla/ecommercee/group/dao/GroupDaoTestSuite.java
> +}
Dokładnie w testach brakuje sprawdzenia co się dzieje z relacjami :)

2020-11-12 11:39 UTC, IngaPanczyk commented on src/test/java/com/kodilla/ecommercee/group/dao/GroupDaoTestSuite.java
> +}
Ja robiłam testy dla Product i sprawdziłam, co się stanie z grupą jeśli usunę produkt. Natomiast test dotyczący sprawdzenia, co się stanie z produktem jak usuniesz grupę moim zdaniem powinien znaleźć się tutaj. Według mnie dotyczy on właśnie operacji usuwania grupy.

2020-11-12 11:40 UTC, IngaPanczyk requested changes
Moim zdaniem nadal brakuje sprawdzenia relacji. Czyli co się stanie z produktem, jeśli usuniesz grupę.

2020-11-13 21:06 UTC, andzia0520 requested changes

2020-11-13 21:06 UTC, andzia0520 commented on src/test/java/com/kodilla/ecommercee/group/dao/GroupDaoTestSuite.java
> +
tu moim zdanie brakuje ustawienia grupy w  product1

2020-11-13 21:06 UTC, andzia0520 commented on src/test/java/com/kodilla/ecommercee/group/dao/GroupDaoTestSuite.java
> +        Assert.assertTrue(readProduct.isPresent());
jak usuwamy grupę to usuwają się produkty więc assertFalse  przy readProduct

2020-11-14 08:04 UTC, Hamonnah commented on src/test/java/com/kodilla/ecommercee/group/dao/GroupDaoTestSuite.java
> +
Dzięki, tego mi brakowało.

2020-11-14 08:05 UTC, Hamonnah commented on src/test/java/com/kodilla/ecommercee/group/dao/GroupDaoTestSuite.java
> +}
Dzieki, teraz juz wszystko powinno być ok.

2020-11-14 09:33 UTC, andzia0520 approved these changes

2020-11-15 09:29 UTC, piotr-grosicki approved these changes

2020-11-15 09:29 UTC, merged