Jdp201001 34
piotr-grosicki/project-jdp-2010-01 pull request #49
Opened 2020-11-11 15:02 UTC by IngaPanczyk

2020-11-11 19:11 UTC, Ryba218 commented on src/main/java/com/kodilla/ecommercee/domain/GroupDto.java
>      public GroupDto(String groupName) {
wydaje mi się, że pole List<Product> productList powinno być List<ProductDto> productList

2020-11-11 19:42 UTC, Ryba218 approved these changes

2020-11-11 21:25 UTC, piotr-grosicki requested changes
cos jest nie tak z ta brancha, spojrz na commity - sa rowniez takie, ktore raczej nie byly robione w ramach tego zadania. odbilas branch na pewno z maina?

2020-11-12 10:10 UTC, IngaPanczyk commented
Usuwam gałąź, zrobiłam nową. Mam nadzieję, że poprawnie.

2020-11-12 10:10 UTC, closed without merging