Jdp201001 34 dodanie relacji order : user
piotr-grosicki/project-jdp-2010-01 pull request #51
Opened 2020-11-12 10:08 UTC by IngaPanczyk

2020-11-12 10:30 UTC, andzia0520 commented on src/main/java/com/kodilla/ecommercee/domain/Order.java
> +    @JoinColumn(name = "USER_OF_ORDERT")
czy nazwa nie byłaby bardziej zrozumiała, jeśli damy np USER_ID?

2020-11-12 10:32 UTC, andzia0520 approved these changes

2020-11-12 11:22 UTC, IngaPanczyk commented on src/main/java/com/kodilla/ecommercee/domain/Order.java
> +    @JoinColumn(name = "USER_OF_ORDERT")
Zgadzam się z Tobą. Poprawione

2020-11-12 11:54 UTC, piotr-grosicki requested changes

2020-11-12 11:54 UTC, piotr-grosicki commented on src/main/java/com/kodilla/ecommercee/domain/User.java
> +    @Column(name = "ORDER_LIST")
tutaj `Column` raczej nie powinno byc, w relacji `OneToMany` nie ma zadnej kolumny zcalajacej po tej stronie

2020-11-12 19:24 UTC, IngaPanczyk commented on src/main/java/com/kodilla/ecommercee/domain/User.java
> +    @Column(name = "ORDER_LIST")
Poprawione

2020-11-13 09:00 UTC, piotr-grosicki approved these changes

2020-11-13 09:00 UTC, merged