JDP201001-40 testy encji Product
piotr-grosicki/project-jdp-2010-01 pull request #56
Opened 2020-11-13 21:35 UTC by dud3k88

Dodany test relacji product - order

2020-11-14 17:25 UTC, andzia0520 requested changes
nie widzę testu który pokazuje co dzieje się jak usuwasz produkt z prduktem a co z orderem

2020-11-15 16:42 UTC, dud3k88 commented
Test poprawiony :)

2020-11-15 20:11 UTC, Ryba218 approved these changes

2020-11-15 21:47 UTC, piotr-grosicki approved these changes

2020-11-15 21:47 UTC, merged